/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helper */

#ifndef _Included_helper
#define _Included_helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helper
 * Method:    print_ndk
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_helper_print_1ndk
  (JNIEnv *, jobject, jstring);

/*
 * Class:     helper
 * Method:    nativeMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_helper_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
